# Name: Jonathan Reyes
# Lab 1
# Course: COSC 3337

In [1]:
import numpy as np


 ### For this task, in the next code cell, how would you:
 ### a)create a python list with elements of the same data type from including 1 to including 5 (as below)?
 ### b)print the python list?
 ### c)print the type of python list using the syntax print(type(variable_name))?
 ### ( 6 points )

In [2]:
""" Creating Arrays and Common Methods """
#a)create a python list with elements of the same data type from including 1 to including 5 (as below)?
python_list = [1, 2, 3, 4,5]

#b)print the python list?

print(python_list)

#c)print the type of python list using the syntax print(type(variable_name))?
print(type(python_list))



[1, 2, 3, 4, 5]
<class 'list'>


### For this task, in the next code cell:
 ### a)convert your previous python list to a numpy array.
 ### b)print the numpy array
 ### c)print the type of numpy array using the syntax print(type(variable_name))
 ### ( 6 points )

In [3]:
#a)convert your previous python list to a numpy array.
numpy_arr = np.array(python_list)

#b)print the numpy array
print(numpy_arr)

#c)print the type of numpy array using the syntax print(type(variable_name))
print(type(numpy_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


 ### For this task, in the next code cell:
 ### a)create a 2d python array with elements of the same data type. Do not use the previous numbers
 ### b)print the python array
 ### c)print the type of python array using the syntax print(type(variable_name))
 ### ( 6 points )

In [4]:
#a)create a 2d python array with elements of the same data type. Do not use the previous numbers
python_2d = [[6,7,8],[9,10,11],[12,13,14]]

#b)print the python array
print(python_2d)
#c)print the type of python array using the syntax print(type(variable_name))
print(type(python_2d))

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]
<class 'list'>


 ### For this task, in the next code cell:
 ### a)convert the python_2d_array variable into a numpy array.
 ### b)print the numpy array
 ### c)print the type of numpy array using the syntax print(type(variable_name))
 ### ( 6 points )

In [5]:
# a)convert the python_2d_array variable into a numpy array.
numpy_2d = np.array(python_2d)

# b)print the numpy array
print(numpy_2d)

# c)print the type of numpy array using the syntax print(type(variable_name))
print(type(numpy_2d))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
<class 'numpy.ndarray'>


### For example, create numpy array where the start is 0 and stop is 15. Try itin the next code cell.
### ( 2 points )

In [6]:
#For example, create numpy array where the start is 0 and stop is 15. Try it in the next code cell.
np.arange(0,15)
#print(numpy_arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### For this task, in the next code cell:
 ### a)create a numpy array from 0 (start) to 15 (stop) with step size of 2.
 ### ( 2 points )

In [7]:
#a)create a numpy array from 0 (start) to 15 (stop) with step size of 2.
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### In the next code cell, how would you create a 2d numpy array with step size 1 into a 5x3 matrix?
 ### ( 2 points )

In [8]:
#In the next code cell, how would you create a 2d numpy array with step size 1 into a 5x3 matrix?
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

 ### In the next two cells:
 ### 1)Create a numpy array of all (15) zeros
 ### 2)Create a 3x5 numpy array of a total of 15 zeros.
 ### 3,4) Do the same for 1s.
 ### ( 16 points )

In [9]:
#1)Create a numpy array of all (15) zeros
print(np.zeros(15))
print('')

#2)Create a 3x5 numpy array of a total of 15 zeros.
print(np.zeros(15).reshape(3,5))
print('')
#3,4) Do the same for 1s.
print(np.ones(15))
print('')
print(np.ones(15).reshape(3,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


###  In the next code cell, how would you create a 3x3 zeros numpy array with data type integer?
 ### ( 2 points )

In [10]:
# In the next code cell, how would you create a 3x3 zeros numpy array with data type integer?
np.zeros(9, dtype=int).reshape(3,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Using the previously learned syntax, how would you create a 5x5 matrix with ones on the diagonal and zeros elsewhere? (hint: this is 'n')
 ### ( 2 points )

In [11]:
# Using the previously learned syntax, how would you create a 5x5 matrix with ones on the diagonal and zeros elsewhere? (hint: this is 'n')
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### What would you replace the '???' with to get the statement below?
 ### ( 4 points )

In [12]:
#What would you replace the '???' with to get the statement below?
A = np.random.randint(0, 100, 20).reshape(4, 5)
print(A)
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

[[78  7  4 90 91]
 [12  3 43 21 24]
 [22 96 94 36 49]
 [48 66 87 25 56]]
The smallest value in A is 3, and is a located at position 6
The largest value in A is 96, and is a located at position 11


 ### Given the above code cell, in the next code cells, how would you:
 ### i)Add A and B?
 ### ii)Add 5 to A (this means for all values of A)
 ### iii)Subtract B from A
 ### iv)Subtract 5 from A
 ### v)Multiply A with B
 ### vi)Multiply A with 5
 ### vii)Divide B from A
 ### viii)Divide 2 from A
 ### ( 24 points )

In [13]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)

#Given the above code cell, in the next code cells, how would you:
 #i)Add A and B?
print(A + B)
print('')
 #ii)Add 5 to A (this means for all values of A)
print(A + 5)
print('')
 #iii)Subtract B from A
print(A - B)
print('')
 #iv)Subtract 5 from A
print(A - 5)
print('')
 #v)Multiply A with B
print(A * B)
print('')
 #vi)Multiply A with 5
print(A * 5)
print('')
 #vii)Divide B from A
print(A / B)
print('')
 #viii)Divide 2 from A
print(A / 2)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44]

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14]

[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10]

[  1   6  15  28  45  66  91 120 153 190 231 276 325 378 435]

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]

[1.         0.66666667 0.6        0.57142857 0.55555556 0.54545455
 0.53846154 0.53333333 0.52941176 0.52631579 0.52380952 0.52173913
 0.52       0.51851852 0.51724138]

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


###  Try changing the -1 to F in the example below and see what happens? Explain why this occurs
 ### ( 2 points )

In [14]:
#Try changing the -1 to F in the example below and see what happens? Explain why this occurs
print(np.where(F%2 == 0, -1, F*100))
print('')
print(np.where(F%2 == 0, F, F*100))

# In the code above when we replace the -1 value with F we are basically changing the input of the value that would 
# change the array if the (F % 2 == 0) operation comes out to be true when parsing through the array, which is why we 
# can see the values (0,2,4,6,10) at the relative indexes where in the original code we would see the value -1


[ -1 100  -1 300  -1 500  -1 700  -1 900  -1]

[  0 100   2 300   4 500   6 700   8 900  10]


###  Using the previous example, how would you complete the rest of the print statements to give the desired results as shown below?
 ### ( 2 points )

In [15]:
#Using the previous example, how would you complete the rest of the print statements to give the desired results as shown below?
A = np.arange(15)
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


###  In the next cell, modify A such that the first 5 elements are 0.
 ### ( 2 points )

In [16]:
#In the next cell, modify A such that the first 5 elements are 0.
A[0:5] = 0
A

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

###  Obtaining a single element can be done using B[row, col]. How would you complete the following print statements to show the correct answer?
 ### ( 12 points )

In [17]:
#Obtaining a single element can be done using B[row, col]. How would you complete the following print statements to show the correct answer?
B = np.arange(50).reshape(5, 10)
print(B)
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


###  How would you get a subset like this?
 ### [ [5, 6],
 ### [15, 16] ]
 ### ( 2 points )

In [18]:
# How would you get a subset like this?
#[ [5, 6],
#[15, 16] ]

B[0:2, 5:7]

array([[ 5,  6],
       [15, 16]])

###  In the next cells, how would you:
 ### a)Return the array where the numbers divisible by 3 are True and the rest are False? Hint see how we did C%2==0
### b)Return how many True were found? Hint see how we did in the above cell.
 ### ( 2 points )

In [19]:
""" Boolean Array Indexing """
C = np.arange(50).reshape(10, 5)
print(C)
print('')
#a)Return the array where the numbers divisible by 3 are True and the rest are False? Hint see how we did C%2==0
print(C%3==0)
#b)Return how many True were found? Hint see how we did in the above cell.
print(f'Sum of all true: {(C%3==0).sum()}')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]
Sum of all true: 17
