# <h1><center>Week 1 Lab (NumPy)</center></h1>
## <h1><center>COSC 3337 Dr. Rizk</center></h1>

## Intro to NumPy

NumPy is the fundamental package for scientific computing with Python. It's used for working with arrays and contains functions for working in the domain of linear algebra, fourier transform, and matrices. In Python we have list, which serve the purpose of arrays, so why do we bother learning NumPy in the first place? Well, NumPy arrays are much faster than traditional Python lists and provide many supporting functions that make working with arrays easier. Part of why they're significantly faster is because the parts that require fast computation are written in C or C++.

Let's begin by importing pandas and learning about the Series data type. If for some reason you don't have pandas installed, you will first have to go to your terminal (or Anaconda Prompt if on Windows) and enter the following:

    conda install numpy
    
Make sure you've already installed [Anaconda](https://www.anaconda.com/)

In [30]:
import numpy as np

### Creating Arrays and Common Methods

The first way of creating a NumPy array is by converting your existing Python list.

In [31]:
python_list = [1, 2, 3, 4, 5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [32]:
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Different examples

In [33]:
""" Different example """
python_list = [10, 22, 3, 47, 54]
print(python_list)
print(type(python_list))

numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[10, 22, 3, 47, 54]
<class 'list'>
[10 22  3 47 54]
<class 'numpy.ndarray'>


In [34]:
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [35]:
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


### Different examples

In [36]:
""" Different example """
python_2d_array=[[13,2,31,47,52],[6,74,82,97,10],[111,12,133,124,156]]
print(python_2d_array)
print(type(python_2d_array))

numpy_2d_array=np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[13, 2, 31, 47, 52], [6, 74, 82, 97, 10], [111, 12, 133, 124, 156]]
<class 'list'>
[[ 13   2  31  47  52]
 [  6  74  82  97  10]
 [111  12 133 124 156]]
<class 'numpy.ndarray'>


However, you are more likely to use some of NumPy's built in methods to generate ndarrays. Here we'll introduce you to a few of these built in methods.

***arange(start, stop, step)*** will return evenly spaced values within a given interval. The default step size is 1.

In [37]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

What if we wanted a 2d array instead? We can call ***reshape(rows, columns)*** on an existing NumPy array. Please note that the product of rows and columns must evaluate to the total number of elements in your current NumPy array.

In [39]:
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

If we'd like to generate an ndarry of zeroes or ones (useful with certain calculations), we could do so by simply calling ***zeros*** or ***ones***. For example:

In [40]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros(15).reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.ones(15).reshape(3, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

You might have noticed that these values defaulted to floats. If for some reason you'd like to use a different type, say, int, you can insert an additional paramater such as ***dtype=int***. See more on dtypes [here](https://numpy.org/doc/stable/user/basics.types.html)

In [44]:
np.ones(15, dtype=int).reshape(3, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Different examples

In [45]:
""" Different examples """
print(np.arange(0,44))
print(" ")
print(np.arange(0,15,5))
print(" ")
print (np.arange(0,25).reshape(5,5))
print(" ")
print(np.zeros(25))
print(" ")
print(np.ones(25,dtype=int).reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
 
[ 0  5 10]
 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


A common matrix used in linear algebra is the identity matrix (an n × n square matrix with ones on the main diagonal and zeros elsewhere). We can generate this in NumPy using ***eye(n)***. 

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Another common use case is to generate an ndarray of random numbers. This can be done in 2 ways. ***rand*** (which will fill the ndarray with random samples from a uniform distribution over [0, 1)), and ***randn*** (which will return a sample (or samples) from the standard normal distribution.) Additionally, we can use ***randint(low, high, size)*** to generate a single or multiple random integers between [low, high). The size parameter specifies how many we'd like. Let's see a few examples.

In [47]:
np.random.rand(5)

array([0.91857774, 0.89622505, 0.68410478, 0.81609206, 0.37915846])

In [48]:
np.random.randn(5)

array([ 0.79580316, -0.12889652,  1.14209652,  1.76724718,  1.39648686])

In [49]:
np.random.randint(1,100)

4

In [50]:
np.random.randint(1, 100, 15)

array([20, 40, 95, 39, 95, 86, 28, 43, 35, 98, 40, 60,  9, 64, 74],
      dtype=int32)

Other common methods that you're likely to encounter in this class include ***min***, ***max***, ***argmin***, and ***argmax***. The only difference between the two arg methods is that they'll instead return the index position of the min/max value. For example:

In [51]:
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[57, 82, 97, 37, 15],
       [79, 46, 70,  2, 34],
       [14, 86, 82, 43, 28],
       [77, 10, 96, 95, 99]], dtype=int32)

In [52]:
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 2, and is a located at position 8
The largest value in A is 99, and is a located at position 19


Lastly, we'll often find ourselves wanting to know the shape (dimensions) of our ndarray. This can be done using ***shape***.

In [53]:
A.shape

(4, 5)

In [54]:
np.shape(A)

(4, 5)

### Different examples

In [55]:
""" Different examples """
""" We can generate the identity matrix by using .eye(num) """
print(np.eye(10))
print(" ")
""" We can use rand to return random samples from the uniform distribution from [0 - 1] """
print( np.random.rand(7))
print(" ")
""" randn will return from the standard normal distribution """
print(np.random.randn(8))
print(" ")
""" return a random int .randint(low,high) """
print(np.random.randint(100,200))
print(" ")
""" Other common methods that you're likely to encounter in this class include min, max, argmin, and
 argmax. The only difference between the two arg methods is that they'll instead return the index
 position of the min/max value. For example: """

A = np.random.randint(0, 50, 20).reshape(4,5)
print(A)
print(" ")
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

""" If we want to check on the size of the array we can use shape """
print(A.shape)
print(" ")
print(np.shape(A))


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
 
[0.59739169 0.32286849 0.31576411 0.16894825 0.58248958 0.92883694
 0.9400078 ]
 
[-0.39428098  0.86253911  1.00900884 -0.58480082  0.72825035  1.13901241
 -0.1536431  -0.44261071]
 
194
 
[[21 29 39 29 41]
 [ 8 46  4 33 17]
 [ 3  2 29  6 22]
 [27 24  6 43 13]]
 
The smallest value in A is 2, and is a located at position 11
The largest value in A is 46, and is a located at position 6
(4, 5)
 
(4, 5)


Great! you now know how to create NumPy arrays and some of the common methods. Let's now look into some common operations we can perform on these arrays.

### Common Operations

In [56]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


### Different example

In [57]:
""" Different examples """

A = np.arange(10, 25)
B = np.arange(3, 33, 3)
C = np.arange(8, 12).reshape(2, 2)
D = np.arange(14, 18).reshape(2, 2)
E = np.arange(30, 45).reshape(3, 5)
F = np.arange(7, 18)

print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)

A: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
B: [ 3  6  9 12 15 18 21 24 27 30]
C:
[[ 8  9]
 [10 11]]
D:
[[14 15]
 [16 17]]
E:
[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
F: [ 7  8  9 10 11 12 13 14 15 16 17]


#### Arithmetic

In [58]:
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [59]:
A + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
A - B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [61]:
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [63]:
A * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [64]:
A / B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [65]:
A / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

### Different examples

In [66]:
""" Different examples """
A = np.arange(10, 25)  
B = np.arange(5, 20)  

print(A + B)
print(" ")
print(A + 7)
print(" ")
print(A - B)
print(" ")
print(A - 3)
print(" ")
print(A * B)
print(" ")
print(A * 6)
print(" ")
print(A / B)
print(" ")
print(A / 5)

[15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
 
[17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
 
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 
[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
 
[ 50  66  84 104 126 150 176 204 234 266 300 336 374 414 456]
 
[ 60  66  72  78  84  90  96 102 108 114 120 126 132 138 144]
 
[2.         1.83333333 1.71428571 1.625      1.55555556 1.5
 1.45454545 1.41666667 1.38461538 1.35714286 1.33333333 1.3125
 1.29411765 1.27777778 1.26315789]
 
[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8]


Note: Becareful dividing by zero. You'll get ***nan*** short for Not a number. 

As you may have noticed, the standard operations \*, +, -, / work element-wise on arrays. If you'd like to instead do matrix multiplication, ***matmul*** can be used. [Here's](https://www.mathsisfun.com/algebra/matrix-multiplying.html) a quick reference in case you forgot how matrix multiplication works.

In [67]:
np.matmul(C, D)

array([[ 2,  3],
       [ 6, 11]])

#### Universal Functions

NumPy also contains [universal functions](https://numpy.org/doc/stable/reference/ufuncs.html), which is a function that operates on ndarrays in an element-by-element fashion. Let's see a few examples.

In [68]:
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [69]:
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

Something that will often come in handy is the ***where(condition, x, y)*** method. This will loop through every element in your ndarray and return a new ndarray that replaces the element with x if the condition is met, and y if the condition is not met. In the example below we're multiplying all odd numbers by 100, else replacing with -1. Try changing the -1 to F in the example below and see what happens.

In [70]:
np.where(F%2==0, -1, F*100)

array([ -1, 100,  -1, 300,  -1, 500,  -1, 700,  -1, 900,  -1])

### Different examples

In [71]:
""" Different examples """
print(np.matmul(D,C))
print(" ")
print(np.sqrt(D))
print(" ")
print(np.log(A))
print(" ")
print(np.where(A%2==0, -1, A*100))

[[ 2  3]
 [ 6 11]]
 
[[0.         1.        ]
 [1.41421356 1.73205081]]
 
[2.30258509 2.39789527 2.48490665 2.56494936 2.63905733 2.7080502
 2.77258872 2.83321334 2.89037176 2.94443898 2.99573227 3.04452244
 3.09104245 3.13549422 3.17805383]
 
[  -1 1100   -1 1300   -1 1500   -1 1700   -1 1900   -1 2100   -1 2300
   -1]


Nice! Now that you know how to create NumPy arrays and perform basic operations on them, let's take a look at how to index and select certain elements.

### Indexing

#### Indexing 1d array
Note: recall that counting starts from 0. Given an array [5, 6, 7, 8], we say that value 5 is at index/position 0.

In [72]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Obtaining a single element will look similar to Python arrays:

In [73]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


We can grab a section using ***A[start_index : stop_index]***. stop_index is not inclusive.

In [74]:
A[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can also modify values in this way.

In [75]:
A[0:10] = 500
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

### Different examples

In [76]:
""" Different examples """
A = np.arange(20)
print(A)
print(" ")
print(f'A[0]: {A[0]}')
print(f'A[15]: {A[15]}')
print(f'A[19]: {A[19]}')
print(A[0:5])
A[0:13] = 20
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 
A[0]: 0
A[15]: 15
A[19]: 19
[0 1 2 3 4]
[20 20 20 20 20 20 20 20 20 20 20 20 20 13 14 15 16 17 18 19]


#### Indexing a 2d array

In [77]:
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Obtaining a single element can be done using ***B[row, col]***.

In [78]:
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


Similar to before, we can also grab a section of interest from this 2darray. Only now we have to specify both the row sections of interest and column sections of interest. ***B[0:2, 3:5]*** says: I want rows 0-2 from B, but only the elements in that row corresponding to columns 3-5. Recall that stop_index is not inclusive. Here stop_index for the rows is 2, and stop_index for the columns is 5.

In [79]:
B[0:2, 3:5]

array([[ 3,  4],
       [13, 14]])

Again, we can also modify values in this way.

In [80]:
B[0:2, 3:5] = -1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, 12, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### Different examples

In [81]:
""" Different examples """
B = np.arange(100).reshape(5, 20)
print(B)
print(f'0th row and 7th col in B: {B[0, 6]}')
print(f'4th row and 9th col in B: {B[3, 8]}')
print(f'5th row and 3rd col in B: {B[4, 2]}')
print(B[2:4, 4:5])
B[2:4, 4:5] = 100
print(B)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
0th row and 7th col in B: 6
4th row and 9th col in B: 68
5th row and 3rd col in B: 82
[[44]
 [64]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43 100  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63 100  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]]


#### Boolean Array Indexing

In [82]:
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

A really cool feature of NumPy is that we can index arrays using comparison operators. This Lets us modify or select only elements meeting some condition. To demonstrate this, lets first see what is returned when we try to use comparison operators with our arrays.

In [83]:
C%2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

We get back an array of the same shape telling us which values in ***C*** satisfy the condition C%2==0 (even values). Recall that 0 is an alias for False, and 1 is an alias for True. Because of this, we can actually call the sum function right off of this array, which will evaluate to the total number of even numbers in ***C***.

In [84]:
(C%2 == 0).sum()

np.int64(25)

Something we'll find ourselves doing more often is passing the boolean array as an index. What this will do is filter out the False elements and only leave us with the elements corresponding to True (even values in our case).

In [85]:
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

### Different examples

In [86]:
""" Different examples """
C = np.arange(100).reshape(10, 10)
print(C)
print(C%10 == 0)
print((C%10 == 0).sum())
print(C[C%10 == 0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]
 [ True False False False False False False False False False]]
10
[ 0 10 20 30 40 50 60 70 80 90]


Congratulations! You now know how to create NumPy arrays, perform common operations on them, and how to index them. There's so much that NumPy can do, but this should cover just about all that you'll need to succeed in this course. Other popular Python libraries used for data science such as Pandas and Matplotlib are built on top of NumPy, so you'll be using a lot of these features alongside those libraries. 